name: portfolio2026-dev

services:
  portfolio2026-dev:
    container_name: portfolio2026-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy

      - traefik.http.routers.portfolio2026-dev.rule=Host(`test.marcespana.com`)
      - traefik.http.routers.portfolio2026-dev.entrypoints=websecure
      - traefik.http.routers.portfolio2026-dev.tls=true
      - traefik.http.routers.portfolio2026-dev.tls.certresolver=letsencrypt
      - traefik.http.services.portfolio2026-dev.loadbalancer.server.port=3000

      - traefik.http.routers.portfolio2026-dev-http.rule=Host(`test.marcespana.com`)
      - traefik.http.routers.portfolio2026-dev-http.entrypoints=web
      - traefik.http.routers.portfolio2026-dev-http.middlewares=portfolio2026-dev-redirect
      - traefik.http.middlewares.portfolio2026-dev-redirect.redirectscheme.scheme=https

networks:
  traefik-proxy:
    external: true