services:
  portfolio2026:
    container_name: portfolio2026
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy

      - traefik.http.routers.portfolio2026.rule=Host(`marcespana.com`)
      - traefik.http.routers.portfolio2026.entrypoints=websecure
      - traefik.http.routers.portfolio2026.tls=true
      - traefik.http.services.portfolio2026.loadbalancer.server.port=3000

      - traefik.http.routers.portfolio2026-http.rule=Host(`marcespana.com`)
      - traefik.http.routers.portfolio2026-http.entrypoints=web
      - traefik.http.routers.portfolio2026-http.middlewares=portfolio2026-redirect
      - traefik.http.middlewares.portfolio2026-redirect.redirectscheme.scheme=https

networks:
  traefik-proxy:
    external: true
